getCron/urls.py
from django.urls import path

from . import views

app_name = 'getCron'

urlpatterns = [
    path('', views.index, name='index'),
    path('lottoNumber', views.lotto_number, name='lotto_number'),
    path('getNumber', views.get_number, name='get_number'),
    path('saveNumber', views.save_number, name='save_number'),
    path('listNumber', views.list_number, name='list_number'),
    path('crollingNumber', views.crolling_number, name='crolling_number'),
    path('numberApi', views.numberApi, name='numberApi'),
    path('crollintIntoSave', views.crolling_into_db, name='crollintIntoSave'),
    # path('getNumber/<int:round_id>/', views.get_number, name='get_number'),
]

lotto/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.conf import settings
# from django.conf.urls.static import static
# from django.conf.urls import url
# import django.contrib.auth.views

from .views.view import *

urlpatterns = [
    path('myApp/', include('myApp.urls', namespace='myApp')),
    path('lotto/', include('getCron.urls', namespace='getCron')),
    path('funTest/', include('funTest.urls', namespace='funTest')),
    path('myData/', include('myData.urls', namespace='myData')),
    # url(r'^$', myApp.views.index(''), name='index'),
    path('admin/', admin.site.urls),
    path('', index),
    path('test', test),
]# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

getCron/models.py
from django.db import models
from .module.crolling_lotto import *


# Create your models here.
class lotto_data(models.Model):
    round = models.IntegerField(default=0)
    prize1 = models.IntegerField(default=0)
    prize2 = models.IntegerField(default=0)
    prize3 = models.IntegerField(default=0)
    prize4 = models.IntegerField(default=0)
    prize5 = models.IntegerField(default=0)
    prize6 = models.IntegerField(default=0)
    bonus = models.IntegerField(default=0)
    drawing_day = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return "str : %d %d %d %d %d %d %d %d" \
               %(self.round, self.prize1, self.prize2, self.prize3, self.prize4, self.prize5, self.prize6, self.bonus)

    def get_lotto_num(self, round_id):
        res = looto_process(int(round_id))
        print(res)

    def get_round(self):
        return self.round

    def get_prize1(self):
        return self.prize1

    def get_prize2(self):
        return self.prize2

    def get_prize3(self):
        return self.prize3

    def get_prize4(self):
        return self.prize4

    def get_prize5(self):
        return self.prize5

    def get_prize6(self):
        return self.prize6

    def get_bonus(self):
        return self.bonus

    def get_drawing_day(self):
        return self.drawing_day

getCron/views.py
# Create your views here.
from django.shortcuts import get_object_or_404, render
from django import forms
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .module.crolling_lotto import *
from getCron.models import lotto_data
from django.urls import reverse
import logging
import json
from django.views.decorators.csrf import csrf_exempt


logger = logging.getLogger('mylogger')


class prizeNumberForm(forms.Form):
    round = forms.IntegerField(widget=forms.HiddenInput())
    prize1 = forms.IntegerField(widget=forms.HiddenInput())
    prize2 = forms.IntegerField(widget=forms.HiddenInput())
    prize3 = forms.IntegerField(widget=forms.HiddenInput())
    prize4 = forms.IntegerField(widget=forms.HiddenInput())
    prize5 = forms.IntegerField(widget=forms.HiddenInput())
    prize6 = forms.IntegerField(widget=forms.HiddenInput())
    bonus = forms.IntegerField(widget=forms.HiddenInput())


class lottoObj:
    def __init__(self, round_id, prize1, prize2, prize3, prize4, prize5, prize6, bonus):
        self.round = round_id
        self.prize1 = prize1
        self.prize2 = prize2
        self.prize3 = prize3
        self.prize4 = prize4
        self.prize5 = prize5
        self.prize6 = prize6
        self.bonus = bonus

    def set_round(self, round_id, prize1, prize2, prize3, prize4, prize5, prize6, bonus):
        self.round = round_id
        self.prize1 = prize1
        self.prize2 = prize2
        self.prize3 = prize3
        self.prize4 = prize4
        self.prize5 = prize5
        self.prize6 = prize6
        self.bonus = bonus


def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")


def lotto_number(request):
    return render(request, 'lottoNumber_form.html')


def crolling_lotto(round_id):
    res = looto_process(round_id)
    if res == "error":
        return 'error'
    else:
        prize_list = res['game']

        '''print('round : %d' % round_id)
        print('prize1 : ' + prize_list[0])
        print('prize2 : ' + prize_list[1])
        print('prize3 : ' + prize_list[2])
        print('prize4 : ' + prize_list[3])
        print('prize5 : ' + prize_list[4])
        print('prize6 : ' + prize_list[5])
        print('bonus : ' + prize_list[6][0])
        '''


        bonus = prize_list[6][0]
        del(prize_list[6])

        data = {
            'round': round_id
            , 'prize1': prize_list[0]
            , 'prize2': prize_list[1]
            , 'prize3': prize_list[2]
            , 'prize4': prize_list[3]
            , 'prize5': prize_list[4]
            , 'prize6': prize_list[5]
            , 'bonus': bonus
        }

        return data, prize_list


def get_number(request):
    round_id = int(request.GET['round_id'])
#     lotto_data = get_object_or_404(lotto_data, pk=round)
#     round_id = int(round)
#     round_id = int(round_id)
    data, prize_list = crolling_lotto(round_id)
    bonus = data['bonus']

    form = prizeNumberForm(data)

    context = {
        'round': round_id
        , 'form': form
        , 'prize_list': prize_list
        , 'bonus': bonus
    }

    return render(request, 'lottoNumber_view.html', context)


def save_number_into_db(game):
    if lotto_data.objects.filter(round=game['round']).exists():
        logger.error('already exist')
        return "fail"
    else:
        round_id = int(game['round'])
        prize1 = int(game['prize1'])
        prize2 = int(game['prize2'])
        prize3 = int(game['prize3'])
        prize4 = int(game['prize4'])
        prize5 = int(game['prize5'])
        prize6 = int(game['prize6'])
        bonus = int(game['bonus'])
        # lottodata = lottoObj(round_id, prize1, prize2, prize3, prize4, prize5, prize6, bonus)
        # print(lottodata.round)
        ld = lotto_data(round=round_id
                        , prize1=prize1
                        , prize2=prize2
                        , prize3=prize3
                        , prize4=prize4
                        , prize5=prize5
                        , prize6=prize6
                        , bonus=bonus
                        )
        ld.save()
        return "save"


def save_number(request):
    round_id = int(request.POST['round'])
    game = {'round': round_id
            , 'prize1': int(request.POST['prize1'])
            , 'prize2': int(request.POST['prize2'])
            , 'prize3': int(request.POST['prize3'])
            , 'prize4': int(request.POST['prize4'])
            , 'prize5': int(request.POST['prize5'])
            , 'prize6': int(request.POST['prize6'])
            , 'bonus': int(request.POST['bonus'])
        }
    res = save_number_into_db(game)
    print(res)

    return HttpResponseRedirect(reverse('getCron:list_number'))

    # selected_choice = lotto_data.choice_set.get(sround=round_id)
    return HttpResponse("save round")


def list_number(request):
    try:
        lotto_list_all = lotto_data.objects.all().order_by('round')
    except (KeyError, lotto_data.DoesNotExist):
        # Redisplay the question voting form.
        return HttpResponse("empty list")
    else:

        lotto_list = []
        for lotto in lotto_list_all:
            lotto_list.append({
                'round': lotto.get_round()
                ,'prize1': lotto.get_prize1()
                ,'prize2': lotto.get_prize2()
                ,'prize3': lotto.get_prize3()
                ,'prize4': lotto.get_prize4()
                ,'prize5': lotto.get_prize5()
                ,'prize6': lotto.get_prize6()
                ,'bonus': lotto.get_bonus()
            })

        context = {
            'lotto_list': lotto_list
        }
        return render(request, 'lottoNumber_list.html', context)


@csrf_exempt #csrf 사용안하기
def numberApi(request):
    # print(request.is_ajax())
    data = json.loads(request.body)
    round_id = data['round']
    data, prize_list = crolling_lotto(round_id)
    print(data)
    return HttpResponse(json.dumps(data))


def crolling_number(request):
    return render(request, 'lottoNumber_crolling.html')


def crolling_into_db(request):
    res = getStartLotto(889)
    # print(type(res))
    for game in res:
        # print(game['round_id'])
        # print(game['game'])
        data = {'round': game['round_id']
            , 'prize1': int(game['game'][0])
            , 'prize2': int(game['game'][1])
            , 'prize3': int(game['game'][2])
            , 'prize4': int(game['game'][3])
            , 'prize5': int(game['game'][4])
            , 'prize6': int(game['game'][5])
            , 'bonus': int(game['game'][6][0])
                }
        # print(data)
        res = save_number_into_db(data)
        print(res)
        # time.sleep(1)

    return HttpResponse("end save")

getCron/templates/lottoNumber_crolling.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>크롤링</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'getCron/css/lottoNumber.css' %}" />
    <script src="{% static '/js/vue.js' %}"></script>
    <script src="{% static '/js/jquery-3.4.1.min.js' %}"></script>
</head>
<body>
    <span>로또번호 크롤링 시작</span>
    <button onclick="start();">시작</button>
    <button onclick="stop();">종료</button>

    <div id="numberListDiv" style="padding-top:25px;">
        <table class="viewTable" id="numberListTbl">
            <tr>
            <td>round</td>
            <td>.1</td>
            <td>.2</td>
            <td>.3</td>
            <td>.4</td>
            <td>.5</td>
            <td>.6</td>
            <td>보너스번호</td>
        </tr>
        </table>
    </div>
</body>


<script src="{% static 'getCron/js/crolling.js' %}"></script>
</html>

getCron/templates/lottoNumber_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'getCron:get_number' %}" method="get">
    회차 :
    <input name="round_id" id="round_id">
    <input type="submit" value="조회">
</form>
</body>
</html>

getCron/templates/lottoNumber_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>로또번호 리스트</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'getCron/css/lottoNumber.css' %}" />
    <script src="{% static '/js/vue.js' %}"></script>
    <script src="{% static '/js/jquery-3.4.1.min.js' %}"></script>
</head>
<body>
    <main id="app">
        <template>
            <div  id="titleText">
            <span>[[message]]</span>
            </div>

            <table id="" class="viewTable">
                <tr>
                    <td>회차</td>
                    <td>.1</td>
                    <td>.2</td>
                    <td>.3</td>
                    <td>.4</td>
                    <td>.5</td>
                    <td>.6</td>
                    <td>보너스번호</td>
                </tr>
                <!--{% for lotto in lotto_list %}
                <tr>
                    <td>{{ lotto.round }}</td>
                    <td>{{ lotto.prize1 }}</td>
                    <td>{{ lotto.prize2 }}</td>
                    <td>{{ lotto.prize3 }}</td>
                    <td>{{ lotto.prize4 }}</td>
                    <td>{{ lotto.prize5 }}</td>
                    <td>{{ lotto.prize6 }}</td>
                    <td>{{ lotto.bonus }}</td>
                </tr>
                {% endfor %}-->

                <tr v-for="(lotto, index) in lottoList" :key="index">
                    <td>[[lotto.round]]</td>
                    <td>[[lotto.prize1]]</td>
                    <td>[[lotto.prize2]]</td>
                    <td>[[lotto.prize3]]</td>
                    <td>[[lotto.prize4]]</td>
                    <td>[[lotto.prize5]]</td>
                    <td>[[lotto.prize6]]</td>
                    <td>[[lotto.bonus]]</td>
                </tr>

            </table>
    </template>
</main>

<script>
       new Vue({
            delimiters: ['[[', ']]'],
            el: '#app',
            data: {
                message: '로또번호 리스트',
                lottoList: []
            },
            created: function () {
                this.getLotto();
            },
            methods: {
                getLotto: function () {
                    {% for lotto in lotto_list %}
                        this.lottoList.push({
                            'round' : {{lotto.round}},
                            'prize1' : {{lotto.prize1}},
                            'prize2' : {{lotto.prize2}},
                            'prize3' : {{lotto.prize3}},
                            'prize4' : {{lotto.prize4}},
                            'prize5' : {{lotto.prize5}},
                            'prize6' : {{lotto.prize6}},
                            'bonus' : {{lotto.bonus}},
                        })
                    {% endfor %}

                }
            }

        });
    </script>
</body>
</html>

getCron/templates/lottoNumber_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>로또번호 {{ round }}회차</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/getCron/css/lottoNumber.css' %}" />
</head>
<body>
<form action="{% url 'getCron:save_number' %}" method="post">
{% csrf_token %}
{% for field in form.hidden_fields %}
    {{field}}
{% endfor %}
<p>{{ round }}회</p>
    <table class="viewTable">
        <tr>
            <td>.1</td>
            <td>.2</td>
            <td>.3</td>
            <td>.4</td>
            <td>.5</td>
            <td>.6</td>
            <td>보너스번호</td>
        </tr>
        <tr>
            {% for prize in prize_list %}
            <td>{{ prize }}</td>
            {% endfor %}
            <td>{{ bonus }}</td>
        </tr>

    </table>
<br>

    <input type="submit" value="DB에 저장하기">
</form>
</body>
</html>