lotto/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.conf import settings
# from django.conf.urls.static import static
# from django.conf.urls import url
# import django.contrib.auth.views

from .views.view import *

urlpatterns = [
    path('myApp/', include('myApp.urls', namespace='myApp')),
    path('lotto/', include('getCron.urls', namespace='getCron')),
    path('funTest/', include('funTest.urls', namespace='funTest')),
    path('myData/', include('myData.urls', namespace='myData')),
    # url(r'^$', myApp.views.index(''), name='index'),
    path('admin/', admin.site.urls),
    path('', index),
    path('test', test),
]# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myApp/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from .views.view import *
from .views.hi import *

app_name = 'myApp'

urlpatterns = [
    path('hi', say_hi),
    path('form', inputForm),
    path('', index, name='index'),
    path('html', index_html, name='index_html'),
    path('html/parent', parent, name='parent'),
    path('html/<int:question_id>/', detail, name='detail'),
    path('html/<int:question_id>/vote/', vote, name='vote'),
    path('html/<int:question_id>/results/', results, name='results'),
]

myApp/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

myApp/views.py
from django.http import HttpResponse
from django.shortcuts import render


def index(request):
    return HttpResponse("Hello, world. You're at the myApp index.")

myApp/views/hi.py
from django.shortcuts import render
from django.http import HttpResponse
# from django.template import loader


def say_hi(request):
    return render(request, 'default/hi.html', {'name':'jiji'})


def inputForm(request):
    return render(request, 'default/input.html')


def rp(request):
    return HttpResponse("Hello, world. You're at the polls index.")


def process(request):
    if request.method == 'GET':
        id = request.GET['id']
    elif request.method == 'POST':
        id = request.POST['id']

    text = 'method : '+request.method+'<br>'
    text += 'my id : '+id
    return HttpResponse(text)

myApp/views/view.py
from django.http import HttpResponse
from django.shortcuts import render

from myApp.models import Choice, Question

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse


def index(request):
    return HttpResponse("Hello, world. You're at the myApp/view index.")


def index_html(request):
    latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'myApp/index.html',context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'myApp/detail.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'myApp/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('myApp:results', args=(question.id,)))


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'myApp/results.html', {'question': question})


def parent(request):
    return render(request, 'parent/base_books.html')

myApp/templates/myApp/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>

<h1>{{ question.question_text }}</h1>
{% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'myApp:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="vote">
</form>

</body>
</html>

myApp/templates/myApp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="/myApp/html/{{ question.id }}">{{ question.question_text }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No myApp art available.</p>
{% endif %}

</body>
</html>

myApp/templates/myApp/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'myApp:detail' question.id %}">Vote again?</a>
</body>
</html>